[package]
name = "mdbook-wavedrom"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
clap = "4.3.2"
mdbook = "0.4.30"
pulldown-cmark = "0.9.3"
pulldown-cmark-to-cmark = "10.0.4"
semver = "1.0.17"
serde_json = "1.0.96"

[dependencies.wavedrom]
path = "../wavedrom-core"
