[package]
name = "wavedrom-wasm"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies.wavedrom]
path = "../wavedrom-core"
