[package]
name = "wavedrom-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies.wavedrom]
path = "../wavedrom-core"
default-features = false
features = ["serde", "embed_font"]

[dependencies]
json5 = "0.4.1"
