# This is a basic workflow to help you get started with Actions
name: Publish to gburghoorn.com/wavedrom

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Publish to gburghoorn.com
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable

      # Build the WaveDrom wasm binary
      - name: WASM Build
        run: |
             cd wavedrom-wasm
             rustup target add wasm32-unknown-unknown
             cargo build --release
             mv ../target/wasm32-unknown-unknown/release/wavedrom_wasm.wasm wavedrom.wasm

      # Download and run TailwindCSS
      - name: TailwindCSS Build
        run: |
             curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/v3.2.4/tailwindcss-linux-x64
             chmod +x tailwindcss-linux-x64
             mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss
             cd wavedrom-wasm
             tailwindcss --minify -i index.scss -o index.css

      # Download and run wasm strip
      - name: WASM Strip
        run: |
             curl -sLO https://github.com/WebAssembly/wabt/releases/download/1.0.33/wabt-1.0.33-ubuntu.tar.gz
             tar -xzf wabt-1.0.33-ubuntu.tar.gz
             chmod +x wabt-1.0.33/bin/wasm-strip
             mv wabt-1.0.33/bin/wasm-strip /usr/local/bin/wasm-strip
             cd wavedrom-wasm
             wasm-strip wavedrom.wasm

      - name: Copy Files into Directory
        run: |
             mkdir public
             mv wavedrom-wasm/index.html public/index.html
             mv wavedrom-wasm/index.js public/index.js
             mv wavedrom-wasm/index.css public/index.css
             mv wavedrom-wasm/wavedrom.wasm public/wavedrom.wasm
             mv wavedrom-wasm/assets public/assets

      - name: Copy Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SCP_HOST }}
          username: ${{ secrets.SCP_USERNAME }}
          key: ${{ secrets.SCP_SSH_KEY }}
          passphrase: ${{ secrets.SCP_SSH_PW }}
          port: ${{ secrets.SCP_PORT }}
          target: ${{ secrets.SCP_PATH }}
          source: "public/*"
          strip_components: 1